services:
  clamav:
    image: clamav/clamav:latest
    container_name: clamav-daemon
    ports:
      - "3310:3310"
    volumes:
      - clamav-db:/var/lib/clamav
      - uploads-data:/app/uploads
    environment:
      - CLAMAV_NO_FRESHCLAMD=false
    healthcheck:
      test: ["CMD", "sh", "-c", "clamdtop || nc -z localhost 3310"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s

  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=clamav_scanner

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - uploads-data:/app/uploads
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    depends_on:
      clamav:
        condition: service_healthy
      mongodb:
        condition: service_started
    restart: unless-stopped

volumes:
  clamav-db:
  mongodb-data:
  uploads-data: